### ISSUE TITLE
No network card detected

### ISSUE THREAD

**Issue by PsySc0rpi0n** [notinaboat/qemu_debian_armhf#2]
Hello

I was following the instructions in the original post from where you build this repository.

**Software and versions**:
Host machine: Debian Buster 4.19.0-14-amd64
qemu version: QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u8)

**Hardware**:
Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
Qualcomm Atheros AR9462 Wireless Network Adapter

I downloaded the 2 files for Buster version here:
[https://http.us.debian.org/debian/dists/buster/main/installer-armhf/current/images/netboot/](url)

Then I tried to use the command you use in [https://github.com/notinaboat/qemu_debian_armhf/blob/master/qemu.sh](url) but without the `-cpu max -smp 4` options because otherwise it hangs at the very beginning. I also didn't include the `-append "root=/dev/vda2"` because the original tutorial is not using it either. And since Buster is a recent version, I used the suggested options from the original turorial, `-device virtio-blk-pci` and `-device virtio-net-pci` instead of the older options.

The complete command I used was:
`qemu-system-aarch64 -M virt -m 4096 \`
`-kernel installer-vmlinuz \`
`-initrd installer-initrd.gz \`
`-drive if=none,file=hda.qcow2,format=qcow2,id=hd \`
`-device virtio-blk-pci,drive=hd -netdev user,id=net0,hostfwd=tcp:127.0.0.1:5555-:22 \`
`-device virtio-net-pci,netdev=net0 \`
`-nographic \`
`-no-reboot`

but when the installer tries to find network adapters, it finds none.
Any ideas why it can't find any adapters? Is the installer trying to find my host machine adapters or the virtual machine adapter?

Thanks
PsySc0rpi0n

**Comment by notinaboat** [comment]
For what its worth, the version of QEMU I have is:
```
% qemu-system-arm --version
QEMU emulator version 5.1.93 (v5.2.0-rc3-9-g944fdc5e27-dirty)
```

Perhaps you could try using a more recent version of QEMU and start by trying the debian images that are included in this repo: https://github.com/notinaboat/qemu_debian_armhf/tree/master/boot
If that works as a starting point, the you could change other settings one by one to suit your needs.

**Comment by PsySc0rpi0n** [comment]
> For what its worth, the version of QEMU I have is:
> 
> ```
> % qemu-system-arm --version
> QEMU emulator version 5.1.93 (v5.2.0-rc3-9-g944fdc5e27-dirty)
> ```
> 
> Perhaps you could try using a more recent version of QEMU and start by trying the debian images that are included in this repo: https://github.com/notinaboat/qemu_debian_armhf/tree/master/boot
> If that works as a starting point, the you could change other settings one by one to suit your needs.

Hi again.

Well, I just installed the buster-backports version, but in the meantime I tried the qemu command with the old options and it worked so I kept going with the instructions.
I hope I can keep asking help here.

While I was trying to extract the kernel out of the disk, I got these errors:

```
$ virt-ls -a hda.qcow2 /boot/
System.map-4.19.0-14-armmp-lpae
config-4.19.0-14-armmp-lpae
initrd.img
initrd.img-4.19.0-14-armmp-lpae
initrd.img.old
lost+found
vmlinuz
vmlinuz-4.19.0-14-armmp-lpae
vmlinuz.old

$ virt-ls -a hda.qcow2 /boot/vmlinuz-4.19.0-14-armmp-lpae /boot/initrd.img-4.19.0-14-armmp-lpae
libguestfs: error: ls0: opendir: /boot/vmlinuz-4.19.0-14-armmp-lpae: Not a directory
libguestfs: error: ls0: opendir: /boot/initrd.img-4.19.0-14-armmp-lpae: Not a directory
```

Do you know why I get this errors?
Thank you
PsySc0rpi0n

**Comment by PsySc0rpi0n** [comment]
Well, at least in my case, I can't copy out both files with a single command as it is in the original tutorial.
I have to copy out one file at a time.
So the copy out command should rather be:

```
$ virt-ls -a hda.qcow2 /boot/vmlinuz-4.19.0-14-armmp-lpae .
$ virt-ls -a hda.qcow2 /boot/initrd.img-4.19.0-14-armmp-lpae .
```

As of your qemu_copyimage.sh script, I think the last line is not needed as it tries to move the copied file to the same place as the previous line do, or am I missing something. I tried your script and I got a error saying exactly that.

**Comment by notinaboat** [comment]
Hi @PsySc0rpi0n,
This repository is simply intended to capture the exact commands that worked for me.
I don't have any particular experience or expertise in relation to QEMU.
If the Makefile in this repository isn't working as-is with an up-to-date version of QEMU, please create an issue with exact steps to reproduce. However, I can't really help with doing things a bit differently, or advise on "the original tutorial".

**Comment by PsySc0rpi0n** [comment]
> Hi @PsySc0rpi0n,
> This repository is simply intended to capture the exact commands that worked for me.
> I don't have any particular experience or expertise in relation to QEMU.
> If the Makefile in this repository isn't working as-is with an up-to-date version of QEMU, please create an issue with exact steps to reproduce. However, I can't really help with doing things a bit differently, or advise on "the original tutorial".

It's not about qemu. It's just a matter of paths, I guess. You assume that the kernel and initrd files are not passed to your script from the same directory where the script is. But in my case, I used the script alone without the Makefile, so the files and the script were in the same folder. That's why that last `mv` command is not needed in my case!
